import 'package:palette/data/models/room.dart';
import 'package:palette/data/models/sample_list_item.dart';
import 'package:palette/data/models/user_profile.dart';

/// The type of in-app prompt to show.
enum PromptType {
  /// Notification opt-in after first room completion.
  notificationOptIn,

  /// Weekend project nudge (Saturday morning).
  weekendProject,

  /// Sample follow-up after 3-5 days.
  sampleFollowUp,

  /// Progress celebration milestone.
  progressCelebration,

  /// Moving day countdown (user entered date).
  movingCountdown,

  /// Seasonal textile/accessory refresh.
  seasonalRefresh,

  /// Spring clocks change reminder.
  clocksChange,

  /// Inactivity re-engagement.
  reEngagement,
}

/// An in-app prompt generated by the prompt engine.
class InAppPrompt {
  const InAppPrompt({
    required this.type,
    required this.title,
    required this.message,
    required this.actionLabel,
    this.route,
    this.icon,
    this.dismissible = true,
  });

  final PromptType type;
  final String title;
  final String message;
  final String actionLabel;
  final String? route;
  final String? icon;
  final bool dismissible;
}

/// Generates contextual in-app prompts based on user state.
class PromptEngine {
  const PromptEngine();

  /// Returns the highest-priority prompt to show (or null if none).
  InAppPrompt? evaluate({
    required UserProfile profile,
    required List<Room> rooms,
    required List<SampleListItem> samples,
    required DateTime now,
  }) {
    // If user has opted out, only show the opt-in prompt (never shown yet).
    final notificationsOff = profile.notificationsEnabled == false;

    // 1. Notification opt-in — show after first room completion, once.
    if (profile.notificationsEnabled == null &&
        profile.notificationOptInPromptShownAt == null &&
        rooms.isNotEmpty) {
      // Check at least one room has a hero colour (= completed first room).
      final hasCompletedRoom = rooms.any((r) => r.heroColourHex != null);
      if (hasCompletedRoom) {
        return const InAppPrompt(
          type: PromptType.notificationOptIn,
          title: 'Stay on track with your project',
          message:
              'Get gentle reminders for sample testing, '
              'weekend projects, and seasonal refresh ideas.',
          actionLabel: 'Turn on reminders',
          dismissible: true,
        );
      }
    }

    // If notifications are off or user hasn't opted in yet, stop here.
    if (notificationsOff || profile.notificationsEnabled == null) return null;

    // Rate-limit: don't show a prompt if one was dismissed recently (24h).
    if (profile.lastPromptDismissedAt != null) {
      final sinceLastDismiss = now.difference(profile.lastPromptDismissedAt!);
      if (sinceLastDismiss < const Duration(hours: 24)) return null;
    }

    // 2. Sample follow-up — 3-5 days after ordering.
    final samplePrompt = _sampleFollowUp(samples, now);
    if (samplePrompt != null) return samplePrompt;

    // 3. Moving day countdown.
    final movingPrompt = _movingCountdown(profile, now);
    if (movingPrompt != null) return movingPrompt;

    // 4. Progress celebration.
    final celebrationPrompt = _progressCelebration(rooms);
    if (celebrationPrompt != null) return celebrationPrompt;

    // 5. Weekend project nudge (Saturday only).
    final weekendPrompt = _weekendProject(rooms, now);
    if (weekendPrompt != null) return weekendPrompt;

    // 6. Seasonal prompts.
    final seasonalPrompt = _seasonalPrompt(now);
    if (seasonalPrompt != null) return seasonalPrompt;

    // 7. Clocks change reminder (late March / late October).
    final clocksPrompt = _clocksChangeReminder(now);
    if (clocksPrompt != null) return clocksPrompt;

    return null;
  }

  InAppPrompt? _sampleFollowUp(List<SampleListItem> samples, DateTime now) {
    final awaiting = samples.where(
      (s) => s.orderedAt != null && s.arrivedAt == null,
    );
    if (awaiting.isEmpty) return null;

    final earliest = awaiting
        .map((s) => s.orderedAt!)
        .reduce((a, b) => a.isBefore(b) ? a : b);
    final daysSinceOrder = now.difference(earliest).inDays;

    if (daysSinceOrder >= 3 && daysSinceOrder <= 14) {
      return const InAppPrompt(
        type: PromptType.sampleFollowUp,
        title: 'Have your samples arrived?',
        message:
            'Test them at different times of day — morning light '
            'and evening light can change everything.',
        actionLabel: 'View testing guide',
        route: '/samples',
      );
    }
    return null;
  }

  InAppPrompt? _movingCountdown(UserProfile profile, DateTime now) {
    if (profile.movingDate == null) return null;

    final daysUntil = profile.movingDate!.difference(now).inDays;
    if (daysUntil < 0 || daysUntil > 90) return null;

    final String message;
    if (daysUntil == 0) {
      message = "It's moving day! Your colour plan is ready to bring to life.";
    } else if (daysUntil <= 7) {
      message =
          '$daysUntil days until moving day. '
          'Time to order paint and confirm your samples.';
    } else if (daysUntil <= 30) {
      message =
          '$daysUntil days to go. '
          'A great time to finalise your room plans and order samples.';
    } else {
      message =
          '$daysUntil days until your move. '
          "Keep building your room plans — you're making great progress.";
    }

    return InAppPrompt(
      type: PromptType.movingCountdown,
      title: 'Moving day countdown',
      message: message,
      actionLabel: 'View rooms',
      route: '/rooms',
    );
  }

  InAppPrompt? _progressCelebration(List<Room> rooms) {
    if (rooms.isEmpty) return null;

    final completedRooms = rooms.where((r) => r.heroColourHex != null).length;

    // Celebrate 3 and 5 room milestones.
    if (completedRooms == 3) {
      return const InAppPrompt(
        type: PromptType.progressCelebration,
        title: "You've planned 3 rooms!",
        message:
            'Your home is coming together. '
            'Connect them with a Red Thread for a cohesive feel.',
        actionLabel: 'View Red Thread',
        route: '/red-thread',
      );
    }

    if (completedRooms == 5) {
      return const InAppPrompt(
        type: PromptType.progressCelebration,
        title: '5 rooms planned — impressive!',
        message:
            "You're building a beautifully cohesive home. "
            'Check your whole-home coherence score.',
        actionLabel: 'See coherence',
        route: '/red-thread',
      );
    }

    return null;
  }

  InAppPrompt? _weekendProject(List<Room> rooms, DateTime now) {
    // Saturday morning only (6am–12pm).
    if (now.weekday != DateTime.saturday) return null;
    if (now.hour < 6 || now.hour >= 12) return null;

    // Find a room that needs work.
    final incomplete = rooms.where((r) => r.heroColourHex == null).toList();
    if (incomplete.isEmpty) return null;

    final room = incomplete.first;
    return InAppPrompt(
      type: PromptType.weekendProject,
      title: 'Weekend project idea',
      message:
          'Your ${room.name} still needs a hero colour. '
          'A great 10-minute task for this morning.',
      actionLabel: 'Set up ${room.name}',
      route: '/rooms/${room.id}',
    );
  }

  InAppPrompt? _seasonalPrompt(DateTime now) {
    // Spring refresh: March–April.
    if (now.month == 3 || now.month == 4) {
      return const InAppPrompt(
        type: PromptType.seasonalRefresh,
        title: 'Spring refresh',
        message:
            'Lighter days are here. Swap heavier textiles for '
            'lighter fabrics and brighter accent colours.',
        actionLabel: 'See suggestions',
        route: '/home',
      );
    }

    // Autumn cosy-up: October–November.
    if (now.month == 10 || now.month == 11) {
      return const InAppPrompt(
        type: PromptType.seasonalRefresh,
        title: 'Autumn cosy-up',
        message:
            'As the evenings draw in, add warmth with chunky throws '
            'and deeper accent tones.',
        actionLabel: 'See suggestions',
        route: '/home',
      );
    }

    return null;
  }

  InAppPrompt? _clocksChangeReminder(DateTime now) {
    // UK clocks change: last Sunday of March and last Sunday of October.
    if (now.month != 3 && now.month != 10) return null;

    // Check if we're in the week before the last Sunday.
    final lastDay = DateTime(now.year, now.month + 1, 0);
    final lastSunday = lastDay.subtract(Duration(days: lastDay.weekday % 7));
    final daysUntil = lastSunday.difference(now).inDays;

    if (daysUntil >= 0 && daysUntil <= 7) {
      final direction = now.month == 3 ? 'forward' : 'back';
      return InAppPrompt(
        type: PromptType.clocksChange,
        title: 'Clocks go $direction soon',
        message:
            'The light in your rooms will shift. '
            'Check how your colours look at different times of day.',
        actionLabel: 'Review rooms',
        route: '/rooms',
      );
    }

    return null;
  }
}
